"""Rebuild the embedded prototype bank from the original CatMeows WAVs."""
from pathlib import Path
import io
import zipfile
root = Path(__file__).resolve().parent.parent
files = sorted((root / 'Assets/Audio/CatMeows').glob('*.wav'))
assert len(files) == 440
archive = io.BytesIO()
with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED) as bank:
    for file in files:
        info = zipfile.ZipInfo(file.name, (2020, 8, 29, 0, 0, 0))
        info.compress_type = zipfile.ZIP_DEFLATED
        bank.writestr(info, file.read_bytes())
with (root / 'Source/MeowBankData.h').open('w') as out:
    out.write('// Generated by Scripts/generate-meow-bank.py. See Assets/Audio/CatMeows/README.md for terms.\n#pragma once\nstatic const unsigned char meowBankData[] = {\n')
    data = archive.getvalue()
    for start in range(0, len(data), 32):
        out.write(','.join(map(str, data[start:start+32])) + ',\n')
    out.write('};\n')
with (root / 'Source/MeowNames.h').open('w') as out:
    out.write('// Generated by Scripts/generate-meow-bank.py; order is the saved parameter mapping.\n#pragma once\ninline juce::StringArray meowNames()\n{\n    return { "Off",\n')
    for file in files:
        context, cat, breed, sex, owner, take = file.stem.split('_')
        label = {'B': 'Brushing', 'F': 'Food', 'I': 'Isolation'}[context]
        out.write(f'        "{cat} / {label} / {take}",\n')
    out.write('    };\n}\n')
